### ISSUE TITLE
Unable to compile unordered_map in clang 3.8.0 and VC++2017

### ISSUE THREAD

**Issue by coder0xff** [serge-sans-paille/frozen#10]
I attempted to compile the unordered_map example provided in README.rst. In clang:
```
In file included from /home/coder0xff/Documents/Plange.build/prefix/src/plange-build/../../../Downloads/frozen/src/frozen/include/frozen/unordered_map.h:27:
/home/coder0xff/Documents/Plange.build/prefix/src/plange-build/../../../Downloads/frozen/src/frozen/include/frozen/bits/pmh.h:155:10: error: chosen constructor is explicit in copy-initialization
  return {items, G, values};
         ^~~~~~~~~~~~~~~~~~
/home/coder0xff/Documents/Plange.build/prefix/src/plange-build/../../../Downloads/frozen/src/frozen/include/frozen/unordered_map.h:78:19: note: in instantiation of function template specialization 'frozen::bits::make_array_of_items<std::pair<frozen::string, int>, 2, 4, frozen::elsa<frozen::string>, frozen::bits::GetKey>' requested here
            bits::make_array_of_items<std::pair<Key, Value>, N, storage_size>(
                  ^
/home/coder0xff/Documents/Plange.build/prefix/src/plange-build/../../../Downloads/frozen/src/frozen/include/frozen/unordered_map.h:82:9: note: in instantiation of member function 'frozen::unordered_map<frozen::string, int, 2, frozen::elsa<frozen::string>, std::equal_to<frozen::string> >::unordered_map' requested here
      : unordered_map{items, Hash{}, KeyEqual{}} {}
        ^
/mnt/c/Users/Brent/Dropbox/Documents/Projects/Plange/source/parlex/include/parlex/builtins/wirth.hpp:41:71: note: in instantiation of member function 'frozen::unordered_map<frozen::string, int, 2, frozen::elsa<frozen::string>, std::equal_to<frozen::string> >::unordered_map' requested here
static constexpr frozen::unordered_map<frozen::string, int, 2> olaf = {
                                                                      ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/tuple:479:19: note: constructor declared here
        constexpr tuple(_UElements&&... __elements)
                  ^
In file included from /mnt/c/Users/Brent/Dropbox/Documents/Projects/Plange/source/parlex/src/behavior.cpp:11:
In file included from /mnt/c/Users/Brent/Dropbox/Documents/Projects/Plange/source/parlex/include/parlex/builtins.hpp:19:
/mnt/c/Users/Brent/Dropbox/Documents/Projects/Plange/source/parlex/include/parlex/builtins/wirth.hpp:41:64: error: constexpr variable 'olaf' must be initialized by a constant expression
static constexpr frozen::unordered_map<frozen::string, int, 2> olaf = {
                                                               ^      ~
2 errors generated.
```

and in VC++ (caveat: has an INTERNAL COMPILER ERROR):
```
1>C:\Users\Brent\Desktop\Plange.build\Downloads\frozen\src\frozen\include\frozen/bits/pmh.h(71): error C2131: expression did not evaluate to a constant
1>C:\Users\Brent\Desktop\Plange.build\Downloads\frozen\src\frozen\include\frozen/bits/pmh.h(71): note: failure was caused by a read of a variable outside its lifetime
1>C:\Users\Brent\Desktop\Plange.build\Downloads\frozen\src\frozen\include\frozen/bits/pmh.h(71): note: see usage of 'iter'
1>C:\Users\Brent\Desktop\Plange.build\Downloads\frozen\src\frozen\include\frozen/bits/pmh.h(71): note: while evaluating 'frozen::elsa<frozen::string>::operator ()(&)'
1>C:\Users\Brent\Desktop\Plange.build\Downloads\frozen\src\frozen\include\frozen/unordered_map.h(78): error C2131: expression did not evaluate to a constant
1>C:\Users\Brent\Desktop\Plange.build\Downloads\frozen\src\frozen\include\frozen/bits/pmh.h(70): note: failure was caused by control reaching the end of a constexpr function
1>C:\Users\Brent\Dropbox\Documents\Projects\Plange\source\parlex\include\parlex/builtins/wirth.hpp(44): fatal error C1903: unable to recover from previous error(s); stopping compilation
1>INTERNAL COMPILER ERROR in 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.10.25017\bin\HostX86\x86\CL.exe'
1>    Please choose the Technical Support command on the Visual C++
1>    Help menu, or open the Technical Support help file for more information
1>Done building project "parlex.vcxproj" -- FAILED.
```

**Comment by serge-sans-paille** [comment]
Concerning the clang, version, clang >= 4.0 is required, sorry about that.

I don't have a working windows machine, so no windows support until someone else handle it :-/

**Comment by codicodi** [comment]
Same example doesn't compile with g++ 7.1 too:
```
$ g++ main.cpp -std=c++14 -I/home/robert/tmp/frozen/include
main.cpp:10:36: error: ‘constexpr const Value& frozen::unordered_map<Key, Value, N, Hash, KeyEqual>::at(const Key&) const [with Key = frozen::string; Value = int; long unsigned int N = 2; Hash = frozen::elsa<frozen::string>; KeyEqual = std::equal_to<frozen::string>]’ called in a constant expression
 constexpr auto val = olaf.at("19"_s);
                                    ^
In file included from main.cpp:1:0:
/home/robert/tmp/frozen/include/frozen/unordered_map.h:101:26: note: ‘constexpr const Value& frozen::unordered_map<Key, Value, N, Hash, KeyEqual>::at(const Key&) const [with Key = frozen::string; Value = int; long unsigned int N = 2; Hash = frozen::elsa<frozen::string>; KeyEqual = std::equal_to<frozen::string>]’ is not usable as a constexpr function because:
   constexpr Value const &at(Key const &key) const {
                          ^~
/home/robert/tmp/frozen/include/frozen/unordered_map.h:105:42: error: expression ‘<throw-expression>’ is not a constant expression
     throw std::out_of_range("unknown key");

```

**Comment by serge-sans-paille** [comment]
@codicodi : that was a limitation of GCC, fixed by #13

**Comment by codicodi** [comment]
Works now, thanks!
